#!/bin/bash

#Shamelessly mostly taken from Chris Truncer vs (insert name).
#Does standard Linux updates/upgrades
#Can include sections that need customization to specific system, ex. enter username

apt update

apt upgrade -y

apt full-upgrade -y

apt --purge autoremove -y

apt clean
apt autoclean

